kind: Deployment
apiVersion: apps/v1
metadata:
  name: fsx-openzfs-csi-controller
  labels:
    {{- include "aws-fsx-openzfs-csi-driver.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controller.replicaCount }}
  {{- with .Values.controller.updateStrategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: fsx-openzfs-csi-controller
      {{- include "aws-fsx-openzfs-csi-driver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fsx-openzfs-csi-controller
        {{- include "aws-fsx-openzfs-csi-driver.labels" . | nindent 8 }}
        {{- if .Values.controller.podLabels }}
        {{- toYaml .Values.controller.podLabels | nindent 8 }}
        {{- end }}
      {{- if .Values.controller.podAnnotations }}
      annotations:
        {{- toYaml .Values.controller.podAnnotations | nindent 8 }}
      {{- end }}
    spec:
      nodeSelector:
        kubernetes.io/os: linux
            {{- with .Values.controller.nodeSelector }}
            {{- toYaml . | nindent 8 }}
            {{- end }}
      serviceAccountName: {{ .Values.controller.serviceAccount.name }}
      priorityClassName: {{ .Values.controller.priorityClassName }}
          {{- with default .Values.controller.affinity }}
      affinity:
            {{- toYaml . | nindent 8 }}
          {{- end }}
      tolerations:
            {{- with .Values.controller.tolerations }}
            {{- toYaml . | nindent 8 }}
            {{- end }}
          {{- with .Values.controller.securityContext }}
      securityContext:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- with .Values.controller.initContainers }}
      initContainers:
            {{- toYaml . | nindent 8 }}
          {{- end }}
      containers:
        - name: fsx-openzfs-plugin
          image: {{ printf "%s:%s" .Values.image.repository (default (printf "v%s" .Chart.AppVersion) (toString .Values.image.tag)) }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --mode={{ .Values.controller.mode }}
            - --endpoint=$(CSI_ENDPOINT)
            - --logging-format={{ .Values.controller.loggingFormat }}
            - --v={{ .Values.controller.logLevel }}
          env:
            - name: CSI_ENDPOINT
              value: unix:///var/lib/csi/sockets/pluginproxy/csi.sock
            - name: CSI_NODE_NAME
              valueFrom:
                 fieldRef:
                   fieldPath: spec.nodeName
            {{- with .Values.controller.region }}
            - name: AWS_REGION
              value: {{ . }}
            {{- end }}
          envFrom:
            {{- with .Values.controller.envFrom }}
            {{- . | toYaml | nindent 12 }}
            {{- end }}
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
          {{- with .Values.controller.volumeMounts }}
          {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: healthz
              containerPort: 9910
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 10
            failureThreshold: 5
          {{- with .Values.controller.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        - name: csi-provisioner
          image: {{ printf "%s:%s" .Values.sidecars.provisioner.image.repository .Values.sidecars.provisioner.image.tag }}
          imagePullPolicy: {{ default .Values.image.pullPolicy .Values.sidecars.provisioner.image.pullPolicy }}
          args:
            - --csi-address=$(ADDRESS)
            - --timeout=5m
            - --extra-create-metadata
            - --v={{ .Values.sidecars.provisioner.logLevel }}
            - --leader-election={{ .Values.sidecars.provisioner.leaderElection.enabled | required "leader election state for csi-provisioner is required, must be set to true || false." }}
                  {{- if .Values.sidecars.provisioner.leaderElection.enabled }}
                  {{- if .Values.sidecars.provisioner.leaderElection.leaseDuration }}
            - --leader-election-lease-duration={{ .Values.sidecars.provisioner.leaderElection.leaseDuration }}
                  {{- end }}
                  {{- if .Values.sidecars.provisioner.leaderElection.renewDeadline}}
            - --leader-election-renew-deadline={{ .Values.sidecars.provisioner.leaderElection.renewDeadline }}
                  {{- end }}
                  {{- if .Values.sidecars.provisioner.leaderElection.retryPeriod }}
            - --leader-election-retry-period={{ .Values.sidecars.provisioner.leaderElection.retryPeriod }}
                  {{- end }}
                  {{- end }}
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
                  {{- with .Values.sidecars.provisioner.env }}
                  {{- . | toYaml | nindent 12 }}
                  {{- end }}
          envFrom:
                  {{- with .Values.controller.envFrom }}
                  {{- . | toYaml | nindent 12 }}
                  {{- end }}
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
                {{- with default .Values.controller.resources .Values.sidecars.provisioner.resources }}
          resources:
                  {{- toYaml . | nindent 12 }}
                {{- end }}
                {{- with .Values.sidecars.provisioner.securityContext }}
          securityContext:
                  {{- toYaml . | nindent 12 }}
                {{- end }}
        - name: csi-snapshotter
          image: {{ printf "%s:%s" .Values.sidecars.snapshotter.image.repository .Values.sidecars.snapshotter.image.tag }}
          imagePullPolicy: {{ default .Values.image.pullPolicy .Values.sidecars.snapshotter.image.pullPolicy }}
          args:
            - --csi-address=$(ADDRESS)
            - --leader-election=true
            - --v={{ .Values.sidecars.snapshotter.logLevel }}
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
                  {{- with .Values.sidecars.snapshotter.env }}
                  {{- . | toYaml | nindent 12 }}
                  {{- end }}
          envFrom:
                  {{- with .Values.controller.envFrom }}
                  {{- . | toYaml | nindent 12 }}
                  {{- end }}
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
                {{- with default .Values.controller.resources .Values.sidecars.snapshotter.resources }}
          resources:
                  {{- toYaml . | nindent 12 }}
                {{- end }}
                {{- with .Values.sidecars.snapshotter.securityContext }}
          securityContext:
                  {{- toYaml . | nindent 12 }}
                {{- end }}
        - name: csi-resizer
          image: {{ printf "%s:%s" .Values.sidecars.resizer.image.repository .Values.sidecars.resizer.image.tag }}
          imagePullPolicy: {{ default .Values.image.pullPolicy .Values.sidecars.resizer.image.pullPolicy }}
          args:
            - --csi-address=$(ADDRESS)
            - --leader-election=true
            - --timeout=5m
            - --v={{ .Values.sidecars.resizer.logLevel }}
            - --handle-volume-inuse-error=false
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
                  {{- with .Values.sidecars.resizer.env }}
                  {{- . | toYaml | nindent 12 }}
                  {{- end }}
          envFrom:
                  {{- with .Values.controller.envFrom }}
                  {{- . | toYaml | nindent 12 }}
                  {{- end }}
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
                {{- with default .Values.controller.resources .Values.sidecars.resizer.resources }}
          resources:
                  {{- toYaml . | nindent 12 }}
                {{- end }}
                {{- with .Values.sidecars.resizer.securityContext }}
          securityContext:
                  {{- toYaml . | nindent 12 }}
                {{- end }}
        - name: liveness-probe
          image: {{ printf "%s:%s" .Values.sidecars.livenessProbe.image.repository .Values.sidecars.livenessProbe.image.tag }}
          imagePullPolicy: {{ default .Values.image.pullPolicy .Values.sidecars.livenessProbe.image.pullPolicy }}
          args:
            - --csi-address=/csi/csi.sock
            - --health-port=9910
          envFrom:
                  {{- with .Values.controller.envFrom }}
                  {{- . | toYaml | nindent 12 }}
                  {{- end }}
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
                {{- with default .Values.controller.resources .Values.sidecars.livenessProbe.resources }}
          resources:
                  {{- toYaml . | nindent 12 }}
                {{- end }}
                {{- with .Values.sidecars.livenessProbe.securityContext }}
          securityContext:
                  {{- toYaml . | nindent 12 }}
                {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- range .Values.imagePullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      volumes:
        - name: socket-dir
          emptyDir: {}
        {{- with .Values.controller.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
