{{- if .Capabilities.APIVersions.Has "policy/v1/PodDisruptionBudget" }}
apiVersion: policy/v1
{{- else }}
apiVersion: policy/v1beta1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: fsx-openzfs-csi-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aws-fsx-openzfs-csi-driver.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: fsx-openzfs-csi-controller
      {{- include "aws-fsx-openzfs-csi-driver.selectorLabels" . | nindent 6 }}
  {{- if le (.Values.controller.replicaCount | int) 2 }}
  maxUnavailable: 1
  {{- else }}
  minAvailable: 2
  {{- end }}
