---
# Source: aws-fsx-openzfs-csi-driver/templates/clusterrolebinding-csi-node.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fsx-openzfs-csi-node-getter-binding
  labels:
    app.kubernetes.io/part-of: aws-fsx-openzfs-csi-driver
subjects:
  - kind: ServiceAccount
    name: fsx-openzfs-csi-node-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: fsx-openzfs-csi-node-role
  apiGroup: rbac.authorization.k8s.io
