---
# Source: aws-fsx-openzfs-csi-driver/templates/clusterrole-csi-node.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fsx-openzfs-csi-node-role
  labels:
    app.kubernetes.io/part-of: aws-fsx-openzfs-csi-driver
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "patch"]
